[features]
seeds = false
skip-lint = false
[programs.localnet]
pedao_v0_0_1 = "AMuUBpBnpMQzBkYr7JyURsYJKGSNiJYdGMarN9hEmJb7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/tuzin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
